# Generated by Django 4.2.27 on 2026-01-07 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_per_100g', models.DecimalField(blank=True, decimal_places=2, help_text='Calories per 100 grams', max_digits=7, null=True)),
                ('protein_per_100g', models.DecimalField(blank=True, decimal_places=2, help_text='Protein in grams per 100g', max_digits=6, null=True)),
                ('carbs_per_100g', models.DecimalField(blank=True, decimal_places=2, help_text='Carbohydrates in grams per 100g', max_digits=6, null=True)),
                ('fat_per_100g', models.DecimalField(blank=True, decimal_places=2, help_text='Fat in grams per 100g', max_digits=6, null=True)),
                ('fiber_per_100g', models.DecimalField(blank=True, decimal_places=2, help_text='Fiber in grams per 100g', max_digits=6, null=True)),
                ('calories_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Calories per single unit/piece', max_digits=7, null=True)),
                ('protein_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Protein in grams per unit', max_digits=6, null=True)),
                ('carbs_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Carbohydrates in grams per unit', max_digits=6, null=True)),
                ('fat_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Fat in grams per unit', max_digits=6, null=True)),
                ('fiber_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Fiber in grams per unit', max_digits=6, null=True)),
                ('unit_type', models.CharField(choices=[('per_100g', 'Per 100 grams'), ('per_unit', 'Per unit/piece')], default='per_100g', max_length=10)),
                ('gram_equivalent_per_cup', models.DecimalField(blank=True, decimal_places=2, help_text='How many grams in 1 cup of this ingredient', max_digits=6, null=True)),
                ('gram_equivalent_per_tbsp', models.DecimalField(blank=True, decimal_places=2, help_text='How many grams in 1 tablespoon', max_digits=6, null=True)),
                ('gram_equivalent_per_tsp', models.DecimalField(blank=True, decimal_places=2, help_text='How many grams in 1 teaspoon', max_digits=6, null=True)),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='recipes.ingredient')),
            ],
            options={
                'verbose_name_plural': 'Ingredient Nutrition',
            },
        ),
    ]
