# Generated by Django 4.2.27 on 2026-01-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredientnutrition'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientnutrition',
            name='gram_equivalent_per_piece',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='How many grams in 1 piece/unit of this ingredient (e.g., 1 tomato = 150g)', max_digits=6, null=True),
        ),
    ]
