# Generated by Django 4.2.27 on 2026-01-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredientnutrition_gram_equivalent_per_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
