# Generated by Django 4.2.27 on 2026-02-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preference',
            field=models.CharField(choices=[('veg', 'Veg'), ('nonveg', 'Nonveg')], default='veg', max_length=10),
        ),
    ]
