# Generated by Django 4.2.27 on 2026-04-08 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_recipe_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of consumption')),
                ('dish_name', models.CharField(help_text='Name of the dish/food consumed', max_length=200)),
                ('calories', models.DecimalField(decimal_places=2, help_text='Total calories', max_digits=7)),
                ('protein', models.DecimalField(decimal_places=2, help_text='Protein in grams', max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=2, help_text='Carbohydrates in grams', max_digits=6)),
                ('fat', models.DecimalField(decimal_places=2, help_text='Fat in grams', max_digits=6)),
                ('fiber', models.DecimalField(decimal_places=2, default=0, help_text='Fiber in grams', max_digits=6)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the meal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Nutrition Log',
                'verbose_name_plural': 'Daily Nutrition Logs',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='recipes_dai_user_id_7f40d0_idx')],
            },
        ),
    ]
