# Generated by Django 4.2.27 on 2026-04-10 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_dailynutritionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the fitness activity')),
                ('steps', models.PositiveIntegerField(default=0, help_text='Number of steps walked')),
                ('notes', models.TextField(blank=True, help_text='Optional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fitness Log',
                'verbose_name_plural': 'Fitness Logs',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='recipes_fit_user_id_cccd1c_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
