# Generated by Django 4.2.27 on 2026-04-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_userprofile_activitylog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='recipes_act_user_id_98b981_idx',
            old_name='recipes_act_user_id_idx',
        ),
    ]
