# Generated by Django 4.2.27 on 2026-04-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_fitnesslog_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If true, all users can see this recipe; otherwise only the creator.'),
        ),
    ]
