# Generated by Django 4.2.27 on 2026-04-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='thumbnail_url',
            field=models.TextField(blank=True, help_text='Small compressed version used in recipe card lists.', null=True),
        ),
    ]
