# Generated by Django 4.2.27 on 2026-04-18 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0015_fridgeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100)),
                ('category', models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('grain', 'Grain'), ('snack', 'Snack'), ('beverage', 'Beverage'), ('packaged', 'Packaged Food'), ('other', 'Other')], default='other', max_length=20)),
                ('serving_description', models.CharField(default='1 serving', help_text='e.g. "1 piece", "100g", "1 bar"', max_length=100)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fiber', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('thumbnail_url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodPantry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Number of units/servings currently owned', max_digits=8)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_entries', to='recipes.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_pantry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'food_item')},
            },
        ),
    ]
