# Generated by Django 4.2.27 on 2026-04-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_pantry_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesslog',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Body weight recorded on this day (kg)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=6, null=True),
        ),
    ]
