# Generated by Django 4.2.27 on 2026-04-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_alter_fitnesslog_weight_kg_and_more'),
        ('recipes', '0018_pantry_low_stock'),
    ]

    operations = [
    ]
