# Generated by Django 4.2.27 on 2026-05-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_merge_20260430_1447'),
        ('recipes', '0019_pantry_quantity_precision'),
    ]

    operations = [
    ]
